from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from sqlmodel import select
from typing import List
from backend.database import get_session, User
from backend.auth import get_current_user
from backend.estate_models import FamilyMemory, VisualMemory, ExternalArchive

router = APIRouter(prefix="/api/memories", tags=["memories"])

# --- Family Memories ---
@router.get("/family", response_model=List[FamilyMemory])
def get_family_memories(user: User = Depends(get_current_user), session: Session = Depends(get_session)):
    statement = select(FamilyMemory).where(FamilyMemory.user_id == user.id)
    return session.exec(statement).all()

@router.post("/family", response_model=FamilyMemory)
def create_family_memory(memory: FamilyMemory, user: User = Depends(get_current_user), session: Session = Depends(get_session)):
    memory.user_id = user.id
    memory.id = None  # Ensure ID is generated by DB
    session.add(memory)
    session.commit()
    session.refresh(memory)
    return memory

@router.put("/family/{memory_id}", response_model=FamilyMemory)
def update_family_memory(memory_id: int, memory_data: FamilyMemory, user: User = Depends(get_current_user), session: Session = Depends(get_session)):
    db_memory = session.get(FamilyMemory, memory_id)
    if not db_memory or db_memory.user_id != user.id:
        raise HTTPException(status_code=404, detail="Memory not found")
    
    # Update fields
    for key, value in memory_data.model_dump(exclude={"id", "user_id"}).items():
        setattr(db_memory, key, value)
    
    session.add(db_memory)
    session.commit()
    session.refresh(db_memory)
    return db_memory

@router.delete("/family/{memory_id}")
def delete_family_memory(memory_id: int, user: User = Depends(get_current_user), session: Session = Depends(get_session)):
    db_memory = session.get(FamilyMemory, memory_id)
    if not db_memory or db_memory.user_id != user.id:
        raise HTTPException(status_code=404, detail="Memory not found")
    session.delete(db_memory)
    session.commit()
    return {"ok": True}

# --- Visual Memories ---
@router.get("/visual", response_model=List[VisualMemory])
def get_visual_memories(user: User = Depends(get_current_user), session: Session = Depends(get_session)):
    statement = select(VisualMemory).where(VisualMemory.user_id == user.id)
    return session.exec(statement).all()

@router.post("/visual", response_model=VisualMemory)
def create_visual_memory(memory: VisualMemory, user: User = Depends(get_current_user), session: Session = Depends(get_session)):
    memory.user_id = user.id
    memory.id = None
    session.add(memory)
    session.commit()
    session.refresh(memory)
    return memory

@router.put("/visual/{memory_id}", response_model=VisualMemory)
def update_visual_memory(memory_id: int, memory_data: VisualMemory, user: User = Depends(get_current_user), session: Session = Depends(get_session)):
    db_memory = session.get(VisualMemory, memory_id)
    if not db_memory or db_memory.user_id != user.id:
        raise HTTPException(status_code=404, detail="Visual memory not found")
    
    for key, value in memory_data.model_dump(exclude={"id", "user_id"}).items():
        setattr(db_memory, key, value)
    
    session.add(db_memory)
    session.commit()
    session.refresh(db_memory)
    return db_memory

@router.delete("/visual/{memory_id}")
def delete_visual_memory(memory_id: int, user: User = Depends(get_current_user), session: Session = Depends(get_session)):
    db_memory = session.get(VisualMemory, memory_id)
    if not db_memory or db_memory.user_id != user.id:
        raise HTTPException(status_code=404, detail="Visual memory not found")
    session.delete(db_memory)
    session.commit()
    return {"ok": True}

# --- External Archives ---
@router.get("/archives", response_model=List[ExternalArchive])
def get_external_archives(user: User = Depends(get_current_user), session: Session = Depends(get_session)):
    statement = select(ExternalArchive).where(ExternalArchive.user_id == user.id)
    return session.exec(statement).all()

@router.post("/archives", response_model=ExternalArchive)
def create_external_archive(archive: ExternalArchive, user: User = Depends(get_current_user), session: Session = Depends(get_session)):
    archive.user_id = user.id
    archive.id = None
    session.add(archive)
    session.commit()
    session.refresh(archive)
    return archive

@router.put("/archives/{archive_id}", response_model=ExternalArchive)
def update_external_archive(archive_id: int, archive_data: ExternalArchive, user: User = Depends(get_current_user), session: Session = Depends(get_session)):
    db_archive = session.get(ExternalArchive, archive_id)
    if not db_archive or db_archive.user_id != user.id:
        raise HTTPException(status_code=404, detail="Archive not found")
    
    for key, value in archive_data.model_dump(exclude={"id", "user_id"}).items():
        setattr(db_archive, key, value)
    
    session.add(db_archive)
    session.commit()
    session.refresh(db_archive)
    return db_archive

@router.delete("/archives/{archive_id}")
def delete_external_archive(archive_id: int, user: User = Depends(get_current_user), session: Session = Depends(get_session)):
    db_archive = session.get(ExternalArchive, archive_id)
    if not db_archive or db_archive.user_id != user.id:
        raise HTTPException(status_code=404, detail="Archive not found")
    session.delete(db_archive)
    session.commit()
    return {"ok": True}
