"""add_missing_asset_columns

Revision ID: 14d9f7ed9ba1
Revises: ec250ef45965
Create Date: 2026-01-23 20:20:32.509551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14d9f7ed9ba1'
down_revision: Union[str, Sequence[str], None] = 'ec250ef45965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('location', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('purchaseDate', sa.DateTime(), nullable=True))
    op.add_column('assets', sa.Column('maintenanceSchedule', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('thumbnail', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'thumbnail')
    op.drop_column('assets', 'maintenanceSchedule')
    op.drop_column('assets', 'purchaseDate')
    op.drop_column('assets', 'location')
    # ### end Alembic commands ###
