"""add_storage_provider_and_category

Revision ID: 1e6d20bb64d7
Revises: 3648ce386dc0
Create Date: 2026-01-23 17:42:41.074708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '1e6d20bb64d7'
down_revision: Union[str, Sequence[str], None] = '3648ce386dc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('device_info', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_assets_name'), 'assets', ['name'], unique=False)
    op.create_index(op.f('ix_assets_status'), 'assets', ['status'], unique=False)
    op.create_index(op.f('ix_assets_type'), 'assets', ['type'], unique=False)
    op.create_index(op.f('ix_assets_user_id'), 'assets', ['user_id'], unique=False)
    op.drop_column('assets', 'valuation')
    op.create_index(op.f('ix_calendar_events_user_id'), 'calendar_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_index(op.f('ix_external_archives_user_id'), 'external_archives', ['user_id'], unique=False)
    op.create_index(op.f('ix_family_memories_user_id'), 'family_memories', ['user_id'], unique=False)
    op.create_index(op.f('ix_financial_accounts_user_id'), 'financial_accounts', ['user_id'], unique=False)
    op.create_index(op.f('ix_heirlooms_name'), 'heirlooms', ['name'], unique=False)
    op.create_index(op.f('ix_heirlooms_recipient'), 'heirlooms', ['recipient'], unique=False)
    op.create_index(op.f('ix_heirlooms_user_id'), 'heirlooms', ['user_id'], unique=False)
    op.create_index(op.f('ix_home_access_user_id'), 'home_access', ['user_id'], unique=False)
    op.create_index(op.f('ix_insurance_policies_user_id'), 'insurance_policies', ['user_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_user_id'), 'journal_entries', ['user_id'], unique=False)
    op.create_index(op.f('ix_letters_user_id'), 'letters', ['user_id'], unique=False)
    op.create_index(op.f('ix_lifeevent_user_id'), 'lifeevent', ['user_id'], unique=False)
    op.add_column('media_files', sa.Column('storage_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('media_files', sa.Column('doc_category', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_medical_directives_user_id'), 'medical_directives', ['user_id'], unique=False)
    op.create_index(op.f('ix_pets_user_id'), 'pets', ['user_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_index(op.f('ix_timecapsulemessage_user_id'), 'timecapsulemessage', ['user_id'], unique=False)
    op.add_column('users', sa.Column('user_role', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('emotional_context', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('overwhelm_muted', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('deceased_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('onboarding_step', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('font_size', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_utilities_user_id'), 'utilities', ['user_id'], unique=False)
    op.create_index(op.f('ix_vendors_user_id'), 'vendors', ['user_id'], unique=False)
    op.create_index(op.f('ix_visual_memories_user_id'), 'visual_memories', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visual_memories_user_id'), table_name='visual_memories')
    op.drop_index(op.f('ix_vendors_user_id'), table_name='vendors')
    op.drop_index(op.f('ix_utilities_user_id'), table_name='utilities')
    op.drop_column('users', 'font_size')
    op.drop_column('users', 'language')
    op.drop_column('users', 'onboarding_completed')
    op.drop_column('users', 'onboarding_step')
    op.drop_column('users', 'deceased_name')
    op.drop_column('users', 'display_name')
    op.drop_column('users', 'overwhelm_muted')
    op.drop_column('users', 'emotional_context')
    op.drop_column('users', 'user_role')
    op.drop_index(op.f('ix_timecapsulemessage_user_id'), table_name='timecapsulemessage')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_pets_user_id'), table_name='pets')
    op.drop_index(op.f('ix_medical_directives_user_id'), table_name='medical_directives')
    op.drop_column('media_files', 'doc_category')
    op.drop_column('media_files', 'storage_provider')
    op.drop_index(op.f('ix_lifeevent_user_id'), table_name='lifeevent')
    op.drop_index(op.f('ix_letters_user_id'), table_name='letters')
    op.drop_index(op.f('ix_journal_entries_user_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_insurance_policies_user_id'), table_name='insurance_policies')
    op.drop_index(op.f('ix_home_access_user_id'), table_name='home_access')
    op.drop_index(op.f('ix_heirlooms_user_id'), table_name='heirlooms')
    op.drop_index(op.f('ix_heirlooms_recipient'), table_name='heirlooms')
    op.drop_index(op.f('ix_heirlooms_name'), table_name='heirlooms')
    op.drop_index(op.f('ix_financial_accounts_user_id'), table_name='financial_accounts')
    op.drop_index(op.f('ix_family_memories_user_id'), table_name='family_memories')
    op.drop_index(op.f('ix_external_archives_user_id'), table_name='external_archives')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_calendar_events_user_id'), table_name='calendar_events')
    op.add_column('assets', sa.Column('valuation', sa.FLOAT(), nullable=True))
    op.drop_index(op.f('ix_assets_user_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_type'), table_name='assets')
    op.drop_index(op.f('ix_assets_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_name'), table_name='assets')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
